#!/usr/bin/env python3
"""
Synthetic TSP instance generator — produces TSPLIB-format files for MengerFlock.

Usage examples:
    python generate_instances.py --output datasets/train \
        --count 10 --sizes small,medium,large \
        --distributions uniform,clustered,grid,mixed

    python generate_instances.py --output datasets/validation \
        --count 5 --sizes small,medium,large \
        --distributions uniform,clustered
"""

import argparse
import math
import os
import random
from pathlib import Path

# ---------------------------------------------------------------------------
# Size bands: (min_n, max_n)
# ---------------------------------------------------------------------------
SIZE_RANGES = {
    "small":  (50,   100),
    "medium": (200,  500),
    "large":  (1000, 2000),
}

COORD_MAX = 10_000.0  # bounding box: [0, COORD_MAX] x [0, COORD_MAX]


# ---------------------------------------------------------------------------
# Point generators
# ---------------------------------------------------------------------------

def _clamp(v: float, lo: float = 0.0, hi: float = COORD_MAX) -> float:
    return max(lo, min(hi, v))


def generate_uniform(n: int, rng: random.Random) -> list[tuple[float, float]]:
    """Uniformly random points in [0, COORD_MAX]^2."""
    return [(rng.uniform(0, COORD_MAX), rng.uniform(0, COORD_MAX)) for _ in range(n)]


def generate_clustered(n: int, rng: random.Random) -> list[tuple[float, float]]:
    """
    Points drawn around randomly placed cluster centres.
    Number of clusters ~ sqrt(n), spread ~ COORD_MAX / (2 * sqrt(clusters)).
    """
    num_clusters = max(2, int(math.sqrt(n)))
    spread = COORD_MAX / (2 * math.sqrt(num_clusters))

    centres = [
        (rng.uniform(0, COORD_MAX), rng.uniform(0, COORD_MAX))
        for _ in range(num_clusters)
    ]

    points: list[tuple[float, float]] = []
    for i in range(n):
        cx, cy = centres[i % num_clusters]
        x = _clamp(rng.gauss(cx, spread))
        y = _clamp(rng.gauss(cy, spread))
        points.append((x, y))

    rng.shuffle(points)
    return points


def generate_grid(n: int, rng: random.Random) -> list[tuple[float, float]]:
    """
    Points placed on a near-square grid with small random perturbation.
    Actual point count is the nearest perfect square to n; extras are filled
    uniformly so the returned list always has exactly n points.
    """
    cols = max(1, int(math.ceil(math.sqrt(n))))
    rows = max(1, int(math.ceil(n / cols)))

    cell_w = COORD_MAX / cols
    cell_h = COORD_MAX / rows
    jitter_x = cell_w * 0.3
    jitter_y = cell_h * 0.3

    grid_points: list[tuple[float, float]] = []
    for r in range(rows):
        for c in range(cols):
            x = _clamp((c + 0.5) * cell_w + rng.uniform(-jitter_x, jitter_x))
            y = _clamp((r + 0.5) * cell_h + rng.uniform(-jitter_y, jitter_y))
            grid_points.append((x, y))

    rng.shuffle(grid_points)

    # Trim or pad to exactly n points
    if len(grid_points) >= n:
        return grid_points[:n]

    extras = generate_uniform(n - len(grid_points), rng)
    return grid_points + extras


def generate_mixed(n: int, rng: random.Random) -> list[tuple[float, float]]:
    """Half clustered, half uniform."""
    half = n // 2
    points = generate_clustered(half, rng) + generate_uniform(n - half, rng)
    rng.shuffle(points)
    return points


GENERATORS = {
    "uniform":   generate_uniform,
    "clustered": generate_clustered,
    "grid":      generate_grid,
    "mixed":     generate_mixed,
}


# ---------------------------------------------------------------------------
# TSPLIB writer
# ---------------------------------------------------------------------------

def write_tsplib(path: Path, name: str, points: list[tuple[float, float]]) -> None:
    """Write a valid EUC_2D TSPLIB file."""
    lines = [
        f"NAME : {name}",
        f"COMMENT : Generated by MengerFlock",
        f"TYPE : TSP",
        f"DIMENSION : {len(points)}",
        f"EDGE_WEIGHT_TYPE : EUC_2D",
        "NODE_COORD_SECTION",
    ]
    for idx, (x, y) in enumerate(points, start=1):
        lines.append(f"{idx} {x:.1f} {y:.1f}")
    lines.append("EOF")

    path.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Instance generation
# ---------------------------------------------------------------------------

def pick_n(size_key: str, rng: random.Random) -> int:
    lo, hi = SIZE_RANGES[size_key]
    return rng.randint(lo, hi)


def generate_all(
    output_dir: Path,
    prefix: str,
    count: int,
    sizes: list[str],
    distributions: list[str],
    seed: int,
) -> list[dict]:
    """
    Generate `count` instances for every (size, distribution) combination.
    Returns a list of metadata dicts for the summary.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(seed)

    records: list[dict] = []

    for dist in distributions:
        generator = GENERATORS[dist]
        for size in sizes:
            for i in range(1, count + 1):
                n = pick_n(size, rng)
                points = generator(n, rng)

                # e.g. train_uniform_small_001
                instance_name = f"{prefix}_{dist}_{size}_{i:03d}"
                filename = instance_name + ".tsp"
                filepath = output_dir / filename

                write_tsplib(filepath, instance_name, points)

                records.append(
                    {
                        "file": str(filepath),
                        "name": instance_name,
                        "distribution": dist,
                        "size_band": size,
                        "n": n,
                    }
                )

    return records


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate synthetic TSP instances in TSPLIB format.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output directory (created if it does not exist).",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=10,
        help="Number of instances per (size, distribution) combination (default: 10).",
    )
    parser.add_argument(
        "--sizes",
        default="small,medium,large",
        help="Comma-separated list of size bands: small, medium, large (default: all).",
    )
    parser.add_argument(
        "--distributions",
        default="uniform,clustered,grid,mixed",
        help=(
            "Comma-separated list of distributions: "
            "uniform, clustered, grid, mixed (default: all)."
        ),
    )
    parser.add_argument(
        "--prefix",
        default=None,
        help=(
            "Filename prefix (default: last component of --output, "
            "e.g. 'train' for datasets/train)."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Global random seed for reproducibility (default: 42).",
    )
    return parser.parse_args()


def validate_choices(values: list[str], valid: set[str], label: str) -> None:
    bad = [v for v in values if v not in valid]
    if bad:
        raise SystemExit(
            f"Unknown {label}: {bad}. Valid choices: {sorted(valid)}"
        )


def print_summary(records: list[dict], output_dir: Path) -> None:
    total = len(records)
    print(f"\n{'='*60}")
    print(f"  Generated {total} TSP instance(s) in: {output_dir}")
    print(f"{'='*60}")

    # Group by (distribution, size_band) for a compact table
    from collections import defaultdict
    groups: dict = defaultdict(list)
    for r in records:
        groups[(r["distribution"], r["size_band"])].append(r["n"])

    header = f"  {'Distribution':<12}  {'Size band':<8}  {'Count':>5}  {'N range'}"
    print(header)
    print("  " + "-" * (len(header) - 2))

    for (dist, size), ns in sorted(groups.items()):
        n_range = f"{min(ns)}–{max(ns)}" if min(ns) != max(ns) else str(min(ns))
        print(f"  {dist:<12}  {size:<8}  {len(ns):>5}  {n_range}")

    print(f"{'='*60}\n")


def main() -> None:
    args = parse_args()

    sizes = [s.strip() for s in args.sizes.split(",") if s.strip()]
    distributions = [d.strip() for d in args.distributions.split(",") if d.strip()]

    validate_choices(sizes, set(SIZE_RANGES), "sizes")
    validate_choices(distributions, set(GENERATORS), "distributions")

    output_dir = Path(args.output)
    prefix = args.prefix or output_dir.name

    records = generate_all(
        output_dir=output_dir,
        prefix=prefix,
        count=args.count,
        sizes=sizes,
        distributions=distributions,
        seed=args.seed,
    )

    print_summary(records, output_dir)


if __name__ == "__main__":
    main()
